openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: magic-8-balls-controller
    description: Magic 8 Balls Controller
  - name: quotes-controller
    description: Quotes Controller
  - name: words-controller
    description: Words Controller
paths:
  /magic:
    post:
      tags:
        - magic-8-balls-controller
      summary: getMagic8BallAnswer
      operationId: getMagic8BallAnswerUsingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '201':
          description: Created
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Magic8Ball'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /quote:
    get:
      tags:
        - quotes-controller
      summary: getQuoteOfTheDay
      operationId: getQuoteOfTheDayUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /word:
    get:
      tags:
        - words-controller
      summary: getDefinition
      operationId: getDefinitionUsingGET
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Definition'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
components:
  schemas:
    Definition:
      title: Definition
      type: object
      properties:
        definition:
          type: string
        id:
          type: integer
          format: int32
        word:
          type: string
    Magic8Ball:
      title: Magic8Ball
      type: object
      properties:
        answer:
          type: string
        id:
          type: integer
          format: int32
        question:
          type: string
    Question:
      title: Question
      type: object
      properties:
        question:
          type: string
    Quote:
      title: Quote
      type: object
      properties:
        author:
          type: string
        id:
          type: integer
          format: int32
        quote:
          type: string
